INSERT INTO PERSON (ID,NAME,LOCATION,BIRTH_DATE)
VALUES(10001,'Daniel','Johannesburg',sysdate());
INSERT INTO PERSON (ID,NAME,LOCATION,BIRTH_DATE)
VALUES(10002,'Kevin','Durban',sysdate());
INSERT INTO PERSON (ID,NAME,LOCATION,BIRTH_DATE)
VALUES(10003,'John','Cape Town',sysdate());